#!/bin/bash
mkdir -p tmp

counter=0
people=$(ls ../midwest/1200/*.jpg | sort -R | head -n 10)

for p in $people; do
  filename=$(basename $p)
  echo "converting $filename"
  if [ "$counter" -lt 5 ]; then
    convert swoop.png $p -resize 800x -compose Multiply -composite tmp/$filename 
  else
    convert "swoop-r.png" $p -resize 800x -compose Multiply -composite tmp/$filename 
  fi
  let counter+=1
done

cd tmp
echo "making midwest strip"
convert $(basename $people) +append -resize x175 -quality 80 ../midwest.jpg

cd ..
rm tmp/*
